//
// Created by alisson on 27/08/22.
//

#ifndef TAREAEXTRACLASE1_ALISSONRM_PAGEDARRAY_H
#define TAREAEXTRACLASE1_ALISSONRM_PAGEDARRAY_H


class PagedArray {

};


#endif //TAREAEXTRACLASE1_ALISSONRM_PAGEDARRAY_H
